version: '3.8'

services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - airtable-network

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - airtable-network
    depends_on:
      - backend

networks:
  airtable-network:
